[LOADIMGARTSY]
dynaconf_merge = true
MIN_ASPECT_RATIO = 1.6

[NIGHTMODE]
NIGHT_BRIGHTNESS = 10
TIMES = [["12:36", "NIGHT"], ["13:00", "DAY"]]
dynaconf_merge = false

[SLIDESHOW]
DELAY = 30.0
dynaconf_merge = false

[PLUGINS]
ACTIVE = ["COUNTDOWN", "DUMMYFRAME", "LOADIMGARTSY", "NIGHTMODE", "REMOTE", "ZOOM"]
dynaconf_merge = false

[COUNTDOWN]
FILL = "#ff8040"
FONT = "Bearpaw"
SIZE = 490
TIME = "2025-01-03 20:28:21"
NAME = "End"
FORMAT = "DAYS_HOURS_MINUTES_SECONDS"
dynaconf_merge = false

[CLOCKS]
FILL = "#F5F5DC"
FONT = "Roboto"
SIZE = 380
dynaconf_merge = false

[REMOTE]
dynaconf_merge = true
ADDRESS = "localhost"

