[FRAME]
dynaconf_merge=true
MODEL = ""

[PLUGINS]
ACTIVE = [
    "NIGHTMODE",
    "CLOCKS",
    "LOADIMGARTSY",
    "DUMMYFRAME",
    "REMOTE",
    "ZOOM"
]

[NIGHTMODE]
    "TIMES" = [["12:36", "night"],
        ["12:37", "day"],
        ]
    "NIGHT_BRIGHTNESS" = 10

[REMOTE]
ADDRESS="localhost"
PORT=8088