

[FRAME]
LOGLEVEL = "DEBUG"
IMG_SIZE = [
    1024,
    600,
]
DELAY = 60

[PLUGUNS]
AVAILABLE = [
    "ledstrip",
    "loadimgfolder",
    "loadimgurl",
    "loadimgartsy",
    "clocks",
    "samsungframe",
    "dummyframe"
]

ACTIVE = [
    "loadimgurl",
    "samsungframe",
]

[SAMSUNGFRAME]
MODEL = ""

[LOADIMGURL]
IMG_SOURCE_PATH = "https://random.imagecdn.app/1024/600"
HTTP_DOWNLOAD_LIMIT = 10
DELAY = 10

[LOADIMGARTSY]
HTTP_DOWNLOAD_LIMIT=5