dynaconf_merge = true

[FRAME]
dynaconf_merge = true
LOGLEVEL = "INFO"
IMG_SIZE = [
    1024,
    600,
]
DELAY = 60

[PLUGINS]
dynaconf_merge = false
ACTIVE = [
    "LOADIMGURL",
    "REMOTE",
    "SAMSUNGFRAME" # For development change to "DUMMYFRAME" or override in settings.local.toml
]


[LOADIMGURL]
IMG_SOURCE_PATH = "https://random.imagecdn.app/1024/600"
HTTP_DOWNLOAD_LIMIT = 10

[LOADIMGARTSY]
HTTP_DOWNLOAD_LIMIT=5

[REMOTE]
ADDRESS="*" # On Windows change to ADDRESS="localhost" or override in settings.local.toml
#ADDRESS="localhost"
PORT=8088

